#pragma once

#define MK_KINETIC_SPEED
#define MOUSEKEY_INITIAL_SPEED 200
#define MOUSEKEY_MOVE_DELTA 5
#define MOUSEKEY_BASE_SPEED 800
#define MOUSEKEY_DECELERATED_SPEED 300
#define MOUSEKEY_ACCELERATED_SPEED 1500

#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 8
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 16
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 32
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 8

#define LED_CAPS_LOCK_PIN B7    // Red LED
// #define LED_CAPS_LOCK_PIN B6 // Green LED but it is inverted
// #define LED_PIN_ON_STATE 0   // This inverts the On state